'use strict';
const paths={search:'m21 21-5-5 M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M4 12h16m-6-6 6 6-6 6',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M4 21v-2a8 6 0 0 1 16 0v2Z',cart:'M2 3h3l3 13h11l3-10H6 M10 21h.01M18 21h.01',menu:'M3 6h18M3 12h18M3 18h18',close:'m6 6 12 12M6 18 18 6',truck:'M1 4h13v13H1Z M14 9h5l4 5v3h-9 M8 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0 M21 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0',card:'M2 5h20v15H2ZM2 10h20M5 16h5',shield:'M12 2 3 6v6c0 6 9 10 9 10s9-4 9-10V6ZM8 12l3 3 5-6',headset:'M3 14v-3a9 9 0 0 1 18 0v7h-4v-8h4M3 10h4v8H3ZM21 18v3h-7',box:'m12 2 10 5v11l-10 5-10-5V7ZM2 7l10 5 10-5M12 12v11M7 4.5l10 5',leaf:'M3 21 17 7M4 16C-2 5 12 1 22 2c0 12-5 20-18 14',smile:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M7 14c2 5 8 5 10 0M8 8h.01M16 8h.01'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.box}"/></svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.outerHTML=icon(el.dataset.icon));
const items=[{id:1,name:'Freidora de aire 5,5 L',category:'Hogar',sub:'Cocina · Electrodomésticos',price:69990,photo:0},{id:2,name:'Audífonos inalámbricos',category:'Tecnología',sub:'Accesorios · Audio',price:24990,old:29990,photo:1},{id:3,name:'Termo térmico 1 L',category:'Bienestar',sub:'Hidratación',price:16990,photo:2},{id:4,name:'Cama para mascotas',category:'Mascotas',sub:'Descanso y comodidad',price:29990,photo:3},{id:5,name:'Macetero decorativo',category:'Hogar',sub:'Decoración',price:12990,photo:4},{id:6,name:'Mat de yoga',category:'Bienestar',sub:'Movimiento y bienestar',price:19990,old:24990,photo:5}];
const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n);
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let saved=read('nubox-favorites',[]);let favorites=new Set(Array.isArray(saved)?saved.filter(id=>items.some(p=>p.id===id)):[]);
let rawCart=read('nubox-cart',{});let cart={};items.forEach(p=>{let q=Number(rawCart?.[p.id]);if(Number.isInteger(q)&&q>0)cart[p.id]=Math.min(q,99)});
let category='Todas',query='',onlyFavorites=false;
const grid=document.getElementById('products'),dialog=document.getElementById('dialog');
function persist(){try{localStorage.setItem('nubox-favorites',JSON.stringify([...favorites]));localStorage.setItem('nubox-cart',JSON.stringify(cart))}catch{}document.getElementById('cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0)}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function render(){const list=items.filter(p=>(category==='Todas'||(category==='Ofertas'?!!p.old:p.category===category))&&(!onlyFavorites||favorites.has(p.id))&&normalize(p.name+' '+p.category+' '+p.sub).includes(normalize(query)));
document.getElementById('products-title').textContent=onlyFavorites?'Tus favoritos':category==='Todas'?'Productos destacados':category;
document.getElementById('filter-description').hidden=!query;document.getElementById('filter-description').textContent=`${list.length} resultados para «${query}»`;
grid.innerHTML=list.map(p=>`<article class="product">${p.old?'<span class="sale">Oferta</span>':''}<button class="favorite" data-favorite="${p.id}" aria-label="${favorites.has(p.id)?'Quitar de':'Guardar en'} favoritos: ${p.name}" aria-pressed="${favorites.has(p.id)}">${icon('heart')}</button><span role="img" aria-label="${p.name}" class="photo p${p.photo}"></span><div class="product-info"><h3>${p.name}</h3><p class="sub">${p.sub}</p><span class="price">${money(p.price)}</span>${p.old?`<span class="old-price">${money(p.old)}</span>`:''}<button class="add" data-add="${p.id}">Agregar al carrito</button></div></article>`).join('')||'<div class="empty"><p>No encontramos productos en esta selección.</p><button data-reset>Ver todos los productos</button></div>';
document.querySelectorAll('.navigation [data-filter]').forEach(el=>{el.classList.toggle('active',el.dataset.filter===category);el.setAttribute('aria-pressed',String(el.dataset.filter===category))});document.getElementById('favorites').setAttribute('aria-pressed',String(onlyFavorites));persist()}
let toastTimer;function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2400)}
function reset(){category='Todas';query='';onlyFavorites=false;document.getElementById('search').value='';render()}
function scrollProducts(){document.getElementById('productos').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
function open(title,html){document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-content').innerHTML=html;if(!dialog.open)dialog.showModal()}
function showCart(){const selected=items.filter(p=>cart[p.id]);open('Tu carrito',selected.length?selected.map(p=>`<div class="cart-row"><span class="photo p${p.photo}" role="img" aria-label="${p.name}"></span><div class="cart-detail"><h3>${p.name}</h3>${money(p.price)}<div class="quantity"><button data-quantity="${p.id}" data-delta="-1" aria-label="Restar uno: ${p.name}">−</button><span>${cart[p.id]}</span><button data-quantity="${p.id}" data-delta="1" aria-label="Sumar uno: ${p.name}">+</button><button data-remove="${p.id}" aria-label="Quitar ${p.name}">Quitar</button></div></div></div>`).join('')+`<div class="cart-total"><span>Total referencial</span><span>${money(selected.reduce((s,p)=>s+p.price*cart[p.id],0))}</span></div><p class="notice">Esta es una vitrina de muestra. Los pagos y pedidos todavía no están habilitados. Tu selección queda guardada en este navegador.</p>`:'<p>Tu carrito está vacío.</p><button class="primary" data-browse>Explorar productos</button>')}
const info={cuenta:['Mi cuenta','<p>El registro de cuentas aún no está habilitado.</p><p>Puedes explorar el catálogo y guardar favoritos en este navegador.</p>'],ayuda:['¿Cómo podemos ayudarte?','<p>Explora las categorías, busca productos o guarda tus favoritos. El catálogo y los precios son de muestra.</p><p>La atención comercial estará disponible cuando la tienda habilite sus canales de contacto.</p>'],nosotros:['Sobre Nubox','<p>Un mundo de opciones para tu hogar y tu día a día.</p><p>En Nubox reunimos Hogar, Tecnología, Bienestar y Mascotas en un solo lugar.</p>'],preguntas:['Preguntas frecuentes','<h3>¿Puedo comprar?</h3><p>Esta versión permite explorar y preparar un carrito. Todavía no procesa pedidos ni pagos.</p><h3>¿Dónde está Cocina?</h3><p>Los productos de cocina se encuentran dentro de Hogar.</p><h3>¿Se guardan mis favoritos?</h3><p>Sí, en este navegador cuando permite almacenamiento local.</p>'],terminos:['Información de esta vitrina','<p>Los productos, precios y ofertas son referenciales. Las imágenes son propuestas generadas con IA para esta maqueta y no representan fichas técnicas de productos reales.</p><p>Este sitio no procesa pagos, pedidos ni datos de cuentas. Solo almacena favoritos y carrito en tu navegador. Las condiciones comerciales se incorporarán antes de habilitar ventas.</p>'],contacto:['Contacto','<p>Los canales de contacto comercial aún no están configurados.</p><p>La información de contacto se publicará cuando se habilite la tienda.</p>']};
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.filter){category=b.dataset.filter;onlyFavorites=false;query='';document.getElementById('search').value='';render();scrollProducts()}if(b.hasAttribute('data-reset'))reset();if(b.dataset.favorite){let id=Number(b.dataset.favorite);favorites.has(id)?favorites.delete(id):favorites.add(id);render();document.querySelector(`[data-favorite="${id}"]`)?.focus()}if(b.dataset.add){let id=Number(b.dataset.add);cart[id]=Math.min(99,(cart[id]||0)+1);persist();toast('Producto agregado al carrito')}if(b.dataset.info){open(...info[b.dataset.info])}if(b.dataset.quantity){let id=Number(b.dataset.quantity);cart[id]=Math.min(99,cart[id]+Number(b.dataset.delta));if(cart[id]<=0)delete cart[id];persist();showCart();document.querySelector(`[data-quantity="${id}"][data-delta="${b.dataset.delta}"]`)?.focus()}if(b.dataset.remove){delete cart[b.dataset.remove];persist();showCart()}if(b.hasAttribute('data-browse')){dialog.close();scrollProducts()}});
document.querySelector('.search').addEventListener('submit',e=>{e.preventDefault();query=document.getElementById('search').value.trim();category='Todas';onlyFavorites=false;render();scrollProducts()});
document.getElementById('search').addEventListener('input',e=>{query=e.target.value.trim();render()});document.getElementById('favorites').onclick=()=>{onlyFavorites=!onlyFavorites;category='Todas';query='';document.getElementById('search').value='';render();scrollProducts()};document.getElementById('show-all').onclick=()=>{reset();scrollProducts()};document.getElementById('cart').onclick=showCart;document.getElementById('close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});document.getElementById('year').textContent=new Date().getFullYear();render();

